server:
  port: 8191
spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/dearsrini22/spring-cloud-config-store.git
          clone-on-start: true
          search-paths:
           - '*service'



