my:
  greeting: Hello from service one

server:
  port: 8191

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: file:///D:/BACKUP/gitcode/spring-cloud-config-store
          searchPaths:
           - '*service'
