service:
  greeting: Hello from service one

server:
  port: 8191

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dearsrini22/spring-cloud-config-store.git
          searchPaths:
           - '*service'
