my:
  greeting: Hello from service one


spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/dearsrini22/spring-cloud-config-store.git
          searchPaths:
           - '*service'
