server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dearsrini22/spring-cloud-config-store
          search-paths:
           - '*service'



